# EVE Online Character Tracker - Docker Compose Configuration
# Created by: ThrainthepainNow
# Last Updated: 2025-05-04 16:06:31
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: eve-tracker-mongodb
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      TZ: UTC
    networks:
      - eve-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eve-tracker-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      PORT: ${PORT:-5000}
      MONGO_URI: ${MONGO_URI:-mongodb://root:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongodb:27017/eve-tracker?authSource=admin}
      CLIENT_URL: ${CLIENT_URL:-http://localhost}
      SERVER_URL: ${SERVER_URL:-http://localhost:5000}
      EVE_CLIENT_ID: ${EVE_CLIENT_ID:-your_client_id}
      EVE_CLIENT_SECRET: ${EVE_CLIENT_SECRET:-your_client_secret}
      SESSION_SECRET: ${SESSION_SECRET:-session_secret_placeholder}
      NODE_ENV: ${NODE_ENV:-production}
      WEBSITE_NAME: ${WEBSITE_NAME:-EVE Character Tracker}
      TZ: UTC
    ports:
      - "${BACKEND_PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./uploads:/app/uploads
    networks:
      - eve-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: eve-tracker-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      SERVER_PROTOCOL: ${SERVER_PROTOCOL:-http}
      FULL_DOMAIN: ${FULL_DOMAIN:-localhost}
      BACKEND_PORT: ${BACKEND_PORT:-5000}
      SSL_MODE: ${SSL_MODE:-skip}
      TZ: UTC
    ports:
      - "${FRONTEND_PORT:-80}:80"
      - "443:443"
    networks:
      - eve-network
    volumes:
      - ./client/public:/usr/share/nginx/html/custom-assets
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ssl_certs:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot

networks:
  eve-network:
    driver: bridge
    name: eve-network

volumes:
  mongo_data:
    name: eve-tracker-mongodb-data
  ssl_certs:
    name: eve-tracker-ssl-certs